# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/sam/Documents/UE5.3.2
GAMEPROJECTFILE =/home/sam/Documents/GitHub/UnrealSource_ObstacleAssault/UnrealLearningKit.uproject

TARGETS = \
	UnrealLearningKit-Linux-DebugGame  \
	UnrealLearningKit-Linux-Shipping  \
	UnrealLearningKit \
	UnrealLearningKitEditor-Linux-DebugGame  \
	UnrealLearningKitEditor-Linux-Shipping  \
	UnrealLearningKitEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend UnrealLearningKitEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UnrealLearningKitEditor-Linux-Debug


UnrealLearningKit-Linux-DebugGame:
	 $(PROJECTBUILD) UnrealLearningKit Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLearningKit-Linux-Shipping:
	 $(PROJECTBUILD) UnrealLearningKit Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLearningKit:
	 $(PROJECTBUILD) UnrealLearningKit Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLearningKitEditor-Linux-DebugGame:
	 $(PROJECTBUILD) UnrealLearningKitEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLearningKitEditor-Linux-Shipping:
	 $(PROJECTBUILD) UnrealLearningKitEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLearningKitEditor:
	 $(PROJECTBUILD) UnrealLearningKitEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
